import { newId } from "./id";
import type { Player } from "./types";

/** Ukázkoví hráči, aby byla aplikace ihned použitelná. */
export function createDemoPlayers(): Player[] {
  const base: Omit<Player, "id">[] = [
    {
      firstName: "Tomáš",
      lastName: "Novák",
      nickname: "Tom",
      birthYear: 1994,
      mainPosition: "CM",
      secondaryPositions: ["AM"],
      foot: "right",
      number: 8,
      note: "Kapitánský typ, dobrá rozehrávka.",
      availability: "available",
    },
    {
      firstName: "Jan",
      lastName: "Černík",
      nickname: "Čerňas",
      birthYear: 1995,
      mainPosition: "CM",
      secondaryPositions: ["DM"],
      foot: "right",
      number: 6,
      note: "",
      availability: "available",
    },
    {
      firstName: "Dominik",
      lastName: "Dietz",
      nickname: "Domi",
      birthYear: 1995,
      mainPosition: "CB",
      secondaryPositions: ["RB"],
      foot: "right",
      number: 4,
      note: "Silný v hlavičkových soubojích.",
      availability: "available",
    },
    {
      firstName: "Vít",
      lastName: "Matulka",
      nickname: "Máťa",
      birthYear: 1996,
      mainPosition: "ST",
      secondaryPositions: ["RW"],
      foot: "left",
      number: 9,
      note: "Rychlý útočník.",
      availability: "available",
    },
    {
      firstName: "Petr",
      lastName: "Svoboda",
      nickname: "Svoba",
      birthYear: 1993,
      mainPosition: "GK",
      secondaryPositions: [],
      foot: "right",
      number: 1,
      note: "Jednička v brance.",
      availability: "available",
    },
    {
      firstName: "Lukáš",
      lastName: "Horák",
      nickname: "Horlas",
      birthYear: 1998,
      mainPosition: "LB",
      secondaryPositions: ["LW"],
      foot: "left",
      number: 3,
      note: "",
      availability: "available",
    },
    {
      firstName: "Martin",
      lastName: "Kučera",
      nickname: "Kuki",
      birthYear: 1997,
      mainPosition: "RB",
      secondaryPositions: ["RW"],
      foot: "right",
      number: 2,
      note: "",
      availability: "uncertain",
    },
    {
      firstName: "Filip",
      lastName: "Bláha",
      nickname: "Fíla",
      birthYear: 1999,
      mainPosition: "CB",
      secondaryPositions: ["DM"],
      foot: "right",
      number: 5,
      note: "",
      availability: "available",
    },
    {
      firstName: "Adam",
      lastName: "Pokorný",
      nickname: "Ády",
      birthYear: 2000,
      mainPosition: "RW",
      secondaryPositions: ["ST", "AM"],
      foot: "left",
      number: 7,
      note: "Kličkař, nebezpečný ze standardek.",
      availability: "available",
    },
    {
      firstName: "Jakub",
      lastName: "Marek",
      nickname: "Kuba",
      birthYear: 1996,
      mainPosition: "LW",
      secondaryPositions: ["LB"],
      foot: "right",
      number: 11,
      note: "",
      availability: "available",
    },
    {
      firstName: "Ondřej",
      lastName: "Veselý",
      nickname: "Ondra",
      birthYear: 2001,
      mainPosition: "AM",
      secondaryPositions: ["CM"],
      foot: "both",
      number: 10,
      note: "Kreativní desítka.",
      availability: "available",
    },
    {
      firstName: "David",
      lastName: "Král",
      nickname: "Dejv",
      birthYear: 1992,
      mainPosition: "DM",
      secondaryPositions: ["CB"],
      foot: "right",
      number: 15,
      note: "Zkušený štít před obranou.",
      availability: "injured",
    },
    {
      firstName: "Michal",
      lastName: "Beneš",
      nickname: "Míša",
      birthYear: 2002,
      mainPosition: "ST",
      secondaryPositions: ["LW"],
      foot: "left",
      number: 19,
      note: "",
      availability: "unavailable",
    },
    {
      firstName: "Radek",
      lastName: "Fiala",
      nickname: "Ríša",
      birthYear: 1994,
      mainPosition: "GK",
      secondaryPositions: [],
      foot: "right",
      number: 12,
      note: "Náhradní brankář.",
      availability: "available",
    },
  ];

  return base.map((p) => ({ ...p, id: newId("pl") }));
}
